sean/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',

    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^noticias/$', 'sean.views.noticias', name='noticias'),
    url(r'^noticias/(\d)/$', 'sean.views.noticia', name="noticia"),
    url(r'^cursos/$', 'sean.views.libros', name='cursos'),
    url(r'^cursos/(\d)/$', 'sean.views.libro', name="curso"),
    url(r'^historia/$', TemplateView.as_view(template_name='historia.html'), name='historia'),
    url(r'^noticias/crear/$', 'sean.views.crear_noticia', name='crear_noticia'),
    url(r'^contactenos/$', 'sean.views.crear_mensaje', name='crear_mensaje'),
)

seanpanama/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from .settings import MEDIA_ROOT

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('sean.urls')),
    url(r'^tutores/', include('tutores.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login$', login, {'template_name': 'login.html', }, name="login"),
    url(r'^logout$', logout, {'template_name': 'index.html', }, name="logout"),
)

sean/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


class Noticia(models.Model):
    titulo = models.CharField(max_length=140)
    contenido = models.TextField(max_length=300)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    usuario_publicador = models.ForeignKey(User)
    
    def __str__(self):
        return self.titulo
    

class Comentario(models.Model):
    contenido = models.TextField(max_length=140)
    comentador = models.CharField(max_length=45)
    comentador_email = models.EmailField()
    noticia = models.ForeignKey(Noticia)
    fecha_comentario = models.DateTimeField(auto_now_add=True)
    aprobacion = models.BooleanField(default=False)
    
    def __str__(self):
        return self.contenido
    
#class Libro(models.Model):
#    nombre = models.CharField(max_length=70)
#    descripcion = models.TextField(max_length=350)
#    portada = models.ImageField(upload_to='portadas')
        
#    def __str__(self):
#        return self.nombre
    

# class Nivel(models.Model):
#     nivel = models.CharField(max_length=35)
#     libros = models.ManyToManyField('Libro')
    
#     def __str__(self):
#         return self.nivel
    
    
class Mensaje(models.Model):
    nombre = models.CharField(max_length=45)
    email = models.EmailField()
    mensaje = models.TextField(max_length=300)
    timestamp = models.DateTimeField("Fecha", auto_now_add=True)
    usuario_publicador = models.ForeignKey(User)
    
    def __str__(self):
        return self.nombre + " - " +self.email

sean/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from .models import Noticia, Mensaje, Comentario

class NoticiaForm(forms.ModelForm):
	class Meta:
		model = Noticia
		exclude = ['usuario_publicador']

class MensajeForm(forms.ModelForm):
	class Meta:
		model = Mensaje
		exclude = ['usuario_publicador']

class ComentarioForm(forms.ModelForm):
	class Meta:
		model = Comentario
		exclude = ['comentador', 'fecha_comentario', 'aprobacion', 'noticia']

sean/views.py
# -*- encoding: utf-8 -*-

from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.core.context_processors import csrf
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse 

from sean.models import Noticia, Comentario
from sean.forms import NoticiaForm, MensajeForm, ComentarioForm
from tutores.models import Libro, Nivel

def noticias(request):
	noticias = Noticia.objects.order_by("-fecha_publicacion").all()
	return render(request,"noticias.html", {"noticias":noticias})

def noticia(request, pk):
	if request.method == 'POST':
		form = ComentarioForm(request.POST)
		if form.is_valid:
			msg = "Su comentario fué enviado y está a la espera de aprobación"
			comentario = form.save( commit=False )
			comentario.comentador = request.user
			noticia = get_object_or_404(Noticia, pk=pk)
			comentario.noticia = noticia
			comentario.save()
			#return HttpResponseRedirect(reverse("noticia_msg", args={id, mensaje}))
			return redirect("/noticias/%s/"%pk)
	else:
		form = ComentarioForm()
		noticia = get_object_or_404(Noticia,pk=pk)
		form = ComentarioForm()
	return render(request,"noticia.html", {"noticia":noticia, 'form':form})

def comentario(request, id):
	noticia = get_object_or_404(Noticia,pk=id)
	return render(request,"noticia.html", {"noticia":noticia})

def libros(request):
	niveles = Nivel.objects.order_by("pk").all()
	return render(request,"libros.html", {"niveles":niveles})

def libro(request, id):
	libro = get_object_or_404(Libro,pk=id)
	return render(request,"libro.html", {"libro":libro})

@login_required
def crear_noticia(request):
	if request.method == 'POST':
		form = NoticiaForm(request.POST)
		if form.is_valid:
			noticia = form.save( commit=False )
			noticia.usuario_publicador = request.user
			noticia.save()
			return redirect("home")
	else:
		form = NoticiaForm()
	return render(request,"form.html", {'form':form,"titulo":"Crear noticia"})

def crear_mensaje(request):
	if request.method == "POST":
		form = MensajeForm(request.POST)
		if form.is_valid:
			mensaje = form.save( commit=False )
			mensaje.usuario_publicador = request.user
			mensaje.save()
			return redirect('home')
	else:
		form = MensajeForm()
	return render(request, "form.html", {"form":form,"titulo":"Contáctenos"})

sean/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="es">
<!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block tittle %}Titulo de mi página{% endblock %}</title>
	<meta name="description" content="En esta pagina web usted encontrará información acerca del ministerio Sean Panamá, tal como nuestra visión, cursos y enlaces de bendición para su vida espiritual">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	{% load static from staticfiles %}
	<link rel="stylesheet" href="{% static "css/normalize.css" %}">
	<link rel="stylesheet" href="{% static "css/main.css" %}">
	<link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static "css/fontello.css" %}">
	<script src="{% static "js/vendor/modernizr-2.6.2.min.js" %}"></script>
</head>
<body>
	<!--[if lt IE 7]>
	<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	<div class="top_green"></div>
	<div class="wrapper">
		<header>
			<a href="{% url 'login' %}">
				<figure>
					<img class="logo_sean" src="{% static "img/logo.gif" %}" alt="Ingresar al sistema" />
					<figcaption>Ingreso al sistema</figcaption>
				</figure>
			</a>
			<h2>Educación cristiana por medio de sean en Panamá</h2>
				<!--div class="social">
					<ul>
						<li>
							<a class="vinculo_social" id="facebook" href="#">Facebook</a>
						</li>
						<li>
							<a class="vinculo_social" id="twitter" href="#">Twitter</a>
						</li>
						<li>
							<a class="vinculo_social" id="google" href="#">Google+</a>
						</li>
					</ul>
				</div-->
			</header>
			<nav>
				<ul>
					{% for item in menu %}
					<li>
						<a class="vinculo {{item.clase}} {% if item.active %} posicionado {% endif %}" href="{{item.url}}" >{{item.name}}</a>
					</li>
					{% endfor %}
				</ul>
			</nav>
			<div class="slider_container">
				<div class="slide_container">
					<div class="slide" data-background="{% static "img/slide1.jpg" %}"></div>
					<div class="slide" data-background="{% static "img/slide2.jpg" %}"></div>
					<div class="slide" data-background="{% static "img/slide3.jpg" %}"></div>
					<button class="prev">&#60</button>
					<button class="next">&#62</button>
				</div>
			</div>
			<div class="cuerpo">
				{% block cuerpo %}Aquí va el cuerpo{% endblock %}
			</div>
			<aside>
				<h2>Últimas noticias</h2>
				{% for noti in ultimas_noticias %}
				<p><h3><a href="{% url 'noticia' noti.pk %}">{{ noti.titulo }}</a></h3></p>
				<p>Publicado por {{ noti.usuario_publicador }} hace {{ noti.fecha_publicacion|timesince }}</p>
				<hr />
				{% endfor %}
			</aside>
		</div>
		{% include "footer.html" %}
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script>
		window.jQuery || document.write('<script src="{% static "js/vendor/jquery-1.10.2.min.js" %}"><\/script>');
		</script>
		<script src="{% static "js/plugins.js" %}"></script>
		<script src="{% static "js/main.js" %}"></script>

		<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
		<script>
		( function(b, o, i, l, e, r) {
			b.GoogleAnalyticsObject = l;
			b[l] || (b[l] = function() {
				(b[l].q = b[l].q || []).push(arguments);
			});
			b[l].l = +new Date;
			e = o.createElement(i);
			r = o.getElementsByTagName(i)[0];
			e.src = '//www.google-analytics.com/analytics.js';
			r.parentNode.insertBefore(e, r);
		}(window, document, 'script', 'ga'));
		ga('create', 'UA-XXXXX-X');
		ga('send', 'pageview');
		</script>
	</body>
	</html>

sean/templates/footer.html
<footer>
	<div class="direccion">
        <h3 class="icon-mail">Contacto</h3>
        <p>&copy; 2014 Sean Panamá</p>
        <p>fucebi@gmail.com</p>
    </div>
	<div class="versiculo">
        <h3 class="icon-lightbulb">Versículo de bendición</h3>
        <p>{{ versiculo }}</p>
    </div>
    <p class="design">Diseño y desarrollo por Alonso Ugalde Aguilar, augaldecr@gmail.com</p>
</footer>

sean/templates/form.html
{% extends "base.html" %}

{% block tittle %}{{titulo}}{% endblock %}

{% block cuerpo %}
<fieldset>
	<legend><h1>{{ titulo }}</h1></legend>
		<div class="tabla">
			<form action="" method="post">{% csrf_token %}
				{{form.as_p}}
				<div class="tabla_botones">
					<input type="reset" value="Borrar">
					<input type="submit" value="Enviar">
				</div>
			</form>
		</div>
</fieldset>
{% endblock %}

sean/templates/historia.html
{% extends  "base.html" %}
{% block tittle %}Historia de Sean{%  endblock%}
{% block cuerpo %}
<h1>Historia de Sean</h1>
<article>
    <p>El concepto original de SEAN se gestó en un área rural del sur de Chile en los años 50. Su creador fue Antonio Barratt, un misionero Anglicano de la SAMS (Sociedad Misionera Sudamericana). Allí, vio la necesidad de comenzar un Instituto Bíblico y Centro de Capacitación Agrícola para las iglesias Mapuches.</p>
    <p>Estos, eran inteligentes, capaces y voluntariosos, pero debido a su mínima educación escolar y el hecho de tener al Español como segundo idioma, no podían entrar en los Seminarios de la ciudad. Además, debido a su condición de agricultores, no podían abandonar sus campos y familias para estudiar. Así, Antonio experimentó con un nuevo sistema de cursos autodidácticos y estudio en grupo para revisar lo aprendido. Este sistema dio generosos dividendos, pero sólo fue usado a un nivel local y reducido.</p>
    <p>El pastor Barratt siguió su ministerio en Paraguay y luego en Tucumán, Argentina. En ese tiempo, 1971, el concepto de ETE (Educación Teológica por Extensión), gestado en Guatemala, ya se había popularizado a través del mundo. ETE, con su objetivo de llevar el Seminario a las iglesias locales, fue la plataforma para que los cursos originados por Antonio llegaran a perfeccionarse y ser conocidos.</p>
    <p>En el año 1971, a pedido de la Iglesia, Antonio formó un pequeño equipo de pastores y profesores de Argentina, Chile y Paraguay, y fundó formalmente a SEAN, que en un inicio significó Seminario por Extensión ANglicano. Pero pronto, por su crecimiento, SEAN fue registrado como una fundación internacional e interdenominacional con su nombre actual - Seminario por Extensión A las Naciones.</p>
    <p>Los primeros cursos fueron Vida Abundante y el Compendio de Teología Pastoral - 6 volúmenes basados en la vida de Cristo.</p>
    <p>Se establecieron los objetivos pedagógicos y prácticos y se repartió la tarea entre el equipo de escritores en sus países de residencia. Estos elaboraban y probaban las lecciones asignadas y luego las enviaban al equipo editor en Tucumán.</p>
    <p>Fue una tarea titánica. Para hacer que las lecciones fueran simples para los estudiantes pero profundas en contenido, el equipo dedicó 600 horas de preparación para cada lección. De hecho, el Compendio de Teología Pastoral se inició en el año 71 y fue terminado en el año 77. Cada lección fue ser rigurosamente probada y corregida hasta que 80% de los estudiantes pudieran lograr 80% de los objetivos.</p>
    <p>Todo el trabajo final se hizo en la casa y garage de la familia Barratt. Nadie se escapaba, ni siquiera las visitas. Fueron varios los obispos y dignatarios visitantes que debieron caminar alrededor de la mesa del comedor compaginando cursos. ¡Eran alentados por el hecho de que debían despejar la mesa para poder almorzar!</p>
    <p>En los primeros años esta obra artesanal sólo fue usado a nivel local. SEAN nunca publicitó sus cursos, pero gradualmente se comenzó a correr la voz y hubo una creciente demanda de usuarios de las más diversas denominaciones a través de América Latina y luego del mundo entero.</p>
    <p>Eventualmente la tarea de escribir, duplicar, armar y enviar los materiales a tantas partes se transformó en una pesadilla para tan pequeño grupo y así surgió la idea que SEAN se concentrara solo en el escribir los cursos y entregar la licencia a los países para que imprimieran en forma local.</p>
    <p>Actualmente los cursos SEAN se usan en unos 100 Países y en más de 70 Idiomas.</p>
    <p>Antonio Barratt y la mayoría de los autores originales ya están jubilados, pero el ministerio continúa. El pequeño equipo SEAN sigue escribiendo, corrigiendo y modernizando los cursos.</p>
    <p>SEAN es una Sociedad Misionera, pero sin Misioneros; es un Ministerio sin muchos Ministros. SEAN provee a las Misiones e Iglesias con herramientas de trabajo, para que capaciten a sus obreros y estos últimos hagan el ministerio y la misión. Y lo hacen con excelencia en Mongolia y en Mozambique; China y Chile; Uzbekistan y Ulster; Albania y Axminster, y estos son sólo algunos de los lugares donde se encuentran los cursos SEAN.</p>
</article>
{% endblock %}

sean/templates/index.html
{% extends  "base.html" %}

{% block tittle %}Bienvenido al sitio web de Sean en Panamá{% endblock %}

{% block cuerpo %}
<h1>Sean Panamá</h1>
<article>
	<p>SEAN Panamá es un ministerio interdenominacional y contamos con permiso y licencia de SEAN Internacional para imprimir y distribuir sus materiales de educación cristiana por extensión a través de FUCEBI (Fundación Centro de Estudios Bíblicos Interdenominacional).</p>
    
    <p>SEAN Internacional (Seminario por Extensión a las Naciones), es un seminario reconocido mundialmente y con 50 años de experiencia. Sus materiales son empleados por muchas organizaciones y seminarios en unos 100 países y en 70 idiomas.</p>

    <p>FUCEBI es una fundación sin fines de lucro avocada a la enseñanza y educación cristiana. Fue fundada en el año 1998 y desde su fundación usamos los materiales de SEAN.</p>

    <p>Nuestra misión es proveer a las Iglesias y ministerios con herramientas de trabajo para que capaciten a sus obreros y estos últimos hagan la obra del ministerio de la edificación del cuerpo de Cristo.</p>

    <blockquote><p>“Y el mismo constituyo a unos, apóstoles; a otros, profetas; a otros, evangelistas; a otros, pastores y maestros, a fin de perfeccionar a los santos para la obra del ministerio, para la edificación del cuerpo de Cristo, hasta que todos lleguemos a la unidad de la fe y del conocimiento del hijo de Dios, a un varón perfecto, a la medida de la estatura de la plenitud de Cristo.”</p>
        <p>Efesios 4:11-13</p></blockquote>
</article>
{% endblock %}

sean/templates/libro.html
{% extends  "base.html" %}

{% block tittle %}Nuestros cursos{% endblock %}

{% block cuerpo %}
    <h1>{{ libro.nombre }}</h1>
		<article class="libro">
			<div>
                <p>{{libro.descripcion}}</p>
            </div>
            <div class="portada"><img src="{{ MEDIA_URL }}{{libro.portada}}"/></div>
		</article>
{% endblock %}

sean/templates/libros.html
{% extends  "base.html" %}

{% block tittle %}Nuestros cursos{% endblock %}

{% block cuerpo %}
    <h1>Nuestros cursos</h1>

{% for nivel in niveles %}
    <h2>{{nivel.nivel}}</h2>
    {% for libro in nivel.libros.all %}
        <article class="libros">
            <div>
                <h3>{{libro.nombre}}</h3>
                <p>{{libro.descripcion|slice:":140"}}...</p>
            </div>
            <div class="portada"><img src="{{ MEDIA_URL }}{{libro.portada}}"/></div>
            <div><a href="{% url 'curso' libro.pk %}">Leer descripción completa</a></div>
        </article>
	{% endfor %}
{% endfor  %}
{% endblock %}

sean/templates/login.html
{% extends "base.html" %}
 
{% block tittle %}Ingreso al sistema{% endblock %}

{% block cuerpo %}
<fieldset class="ingreso">
    <legend><h1>Ingreso al sistema</h1></legend>
    <div class="tabla" id="login">
        <form method="post" action="{% url 'django.contrib.auth.views.login' %}">{% csrf_token %}
            {{form.as_p}}
            <p>
            <input type="submit" value="Ingresar"/>
            <input type="hidden" name="next" value="{{ next }}"/>
        </form>
    </div>
    {% if form.errors %}
        <p>El usuario o contraseña que usted digito son incorrectos, digite un usuario y contraseña validos</p>
    {% endif %}
</fieldset>
{% endblock %}

sean/templates/noticia.html
{% extends  "base.html" %}

{% block tittle %}Noticias y actividades{% endblock %}

{% block cuerpo %}
<h1>{{noticia.titulo}}</h1>
<article>
	<p>{{noticia.contenido}}</p>
	<p>{{noticia.usuario_publicador}}, {{noticia.fecha_publicacion|timesince}}</p>
	<hr />
	{% for comentario in noticia.comentario_set.all %}
		{% if comentario.aprobacion == True %}
			<div class="comentario">
				<p>{{comentario.contenido}}</p>
				<p>Comentario por {{comentario.comentador}}, hace {{comentario.fecha_comentario|timesince}}</p>
			</div>
		{% endif %}
	{% endfor %}
	<fieldset>
	<legend><h3>Enviar comentario</h3></legend>
		<div class="tabla">
			<form action="" method="post">{% csrf_token %}
				{{form.as_p}}
				<div class="tabla_botones">
					<input type="reset" value="Borrar">
					<input type="submit" value="Enviar">
				</div>
			</form>
		</div>
		<p>Los comentarios son enviados y deben esperar aprobación de parte de Sean Panamá</p>
</fieldset>
</article>
{% endblock %}

sean/templates/noticias.html
{% extends  "base.html" %}

{% block tittle %}Noticias y actividades{% endblock %}

{% block cuerpo %}
<h1>Noticias y actividades</h1>
	{% for noticia in noticias %}
		<article>
			<fieldset>
				<legend><h3>{{noticia.titulo}}</h3></legend>
					<p>{{noticia.contenido}}</p>
					<p>{{noticia.usuario_publicador}}, {{noticia.fecha_publicacion|timesince}}</p>
					<a class="mas" href="{% url 'noticia' noticia.pk %}">Leer noticia completa</a>
			</fieldset>
		</article>
	{% endfor %}
{% endblock %}